# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41eb31d7a7d3ede184a45d22d06e2084c9b4c90d2571913764241f3089a139fd6170d865621913f7ab24fc4a31a29185485049de643f88eb8ac37625b0c2a7b3
  facebook_key: 372794152876458
  facebook_secret: 41324e578bc392e14b9baf807f293658
  mandrill_username: hunter@hunterhusar.net
  mandrill_apikey: g5VosTCLBPNbE4VDzDZwJw

test:
  secret_key_base: fe3b265bfe90bef75f8b24aa5c78e13096202eb7a026c54cd20ec9f1a22092d5aa79a543dbd8ad09fe7fd71c80db04b0642c1e39735feb44989b4e7ea7bf6b04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
  mandrill_apikey: <%= ENV["MANDRILL_APIKEY"] %>
